version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_transporte
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: transporte_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pipeline:
    build: .
    container_name: gtfs_pipeline_scheduler
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpassword
      - DB_NAME=transporte_db
    restart: always

volumes:
  postgres_data:
